### ISSUE TITLE
Collect Geo-Spatial Data from the Client

### ISSUE THREAD

**Issue by akaric108** [James-Oswald/Direction-Guesser#28]
There needs to be some mechanism for collecting geo-spatial data from the client. 

Design a view (utilizing the camera, perhaps with a crosshair overlaid) that will collect the GPS data (e.g. `longitude`, `latitude`) and Heading data (e.g. `azimuth`, `pitch`, `roll`) from the phone when the screen is tapped. 

Package the data into a JSON format that's agnostic to the differences between IOS and Android.

And use your own discretion, if you think that `longitude` and `latitude` (for example) aren't the right things to be collecting, then don't; but leave a comment as to why you think so.

**Comment by SharieRhea** [comment]
I've done some looking into Flutter plugins that can accomplish this.

[camera](https://pub.dev/packages/camera) should handle opening the camera view from within the app. I will need to figure out how to overlay this.
[flutter_compass](https://pub.dev/packages/flutter_compass) can provide a compass direction in degrees relative to north. I'm not sure what the accuracy is but it seems like the value is a double.
[geolocator](https://pub.dev/packages/geolocator) seems pretty promising for handling the current location coordinates (long and lat). There does not seem to be a way to get the compass direction though.

Another idea I had was: What if we just have the user actually take a picture? The photo's metadata will include the coordinates, and from a little research it seems like most photos also include directional data in `Exif.GPSInfo.GPSImgDirection`. Of course, this may not be true for every phone camera, so it is probably safer to just grab the coordinates and direction separately from two different libraries.

**Comment by akaric108** [comment]
I found [this one](https://pub.dev/packages/sensor_library) which bundles both things under one library. 

```dart
Gps gps = Gps(inMillis: intervalInMilliseconds);
gps.getRaw().listen((element) {
   var altitude = element.altitude;
   var heading = element.heading;
   var speed = element.speed;
   var latitude = element.latitude;
   var longitude = element.longitude;
   // ...
   // Do your magic here
})
```

Heading might be all we actually need (the number of degrees off of north).

> What if we just have the user actually take a picture? The photo's metadata will include the coordinates, and from a little research it seems like most photos also include directional data in Exif.GPSInfo.GPSImgDirection

This would work if the camera API (`Camera2 API`, on Android) gives us an image with EXIF information, which I'm kind of doubtful of (that would break android's privacy model...) 

Usually EXIF information is embedded into the image by the camera app itself.

To fix that, we could have people upload images (that could play out into another idea in the future..), but then we'd still not be guaranteed of getting anything in the EXIF (I know that my phone's camera app doesn't include such data).

**Comment by SharieRhea** [comment]
> I found [this one](https://pub.dev/packages/sensor_library) which bundles both things under one library.

Nice, I'll take a look.

> This would work if the camera API (`Camera2 API`, on Android) gives us an image with EXIF information, which I'm kind of doubtful of (that would break android's privacy model...)
> 
> Usually EXIF information is embedded into the image by the camera app itself.
> 
> To fix that, we could have people upload images (that could play out into another idea in the future..), but then we'd still not be guaranteed of getting anything in the EXIF (I know that my phone's camera app doesn't include such data).

Right, I had pictured the user taking a photo, then immediately uploading/using that photo as their guess. But you are right, EXIF data is not guaranteed. Library it is!
