### ISSUE TITLE
Create .gitattributes to force linguist to ignore bloat files

### ISSUE THREAD

**Issue by James-Oswald** [James-Oswald/Direction-Guesser#9]
![image](https://github.com/user-attachments/assets/994ed6bf-d691-49cc-97e7-cd8572c551c5)

I dislike seeing all these languages, use a `.gitattributes` to force GitHub linguist to ignore any default files in frontend that include code we have not written. 

How to:
https://stackoverflow.com/questions/19052834/is-it-possible-to-exclude-files-from-git-language-statistics

**Comment by akaric108** [comment]
Tried adding it in the latest commit [as per](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md#vendored-code), but doesn't seem to take effect.

**Comment by akaric108** [comment]
I did write that Makefile, and I'll be maintaining it. In that case then, this issue is closed.
